c_stdlib_version:                                   # [linux]
  - "2.28"                                          # [linux]
docker_image:                                       # [linux]
  - quay.io/condaforge/linux-anvil-alma-x86_64:8    # [linux]

MACOSX_SDK_VERSION:  # [osx and x86_64]
  - "10.15"          # [osx and x86_64]
