{% set version = "1.16.0" %}

package:
  name: c-ares
  version: {{ version }}

source:
  url: https://c-ares.haxx.se/download/c-ares-{{ version }}.tar.gz
  sha256: de058ad7c128156e2db6dc98b8a359924d6f210a1b99dd36ba15c8f839a83a89

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler("c") }}
    - cmake
    - make  # [unix]
  host:
    - msinttypes  # [win and vc<14]

test:
  commands:
    - test -f ${PREFIX}/lib/libcares_static.a     # [not win]
    - test -f ${PREFIX}/include/ares.h            # [not win]
    - test -f ${PREFIX}/lib/libcares${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\include\\ares.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\cares.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cares.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cares_static.lib exit 1  # [win]

about:
  home: https://c-ares.haxx.se/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: This is c-ares, an asynchronous resolver library

extra:
  recipe-maintainers:
    - ocefpaf
    - wesm
    - xhochy
