appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: nJv0xNUcRFsKVBw4N4iUqjGZ2UlPXPEnXJu4flWsig6GNEEeTm2JQdRiUNt+y5Q634kBEC07s6mShIkGdFgBnkwMjQj+MmkEMORJ6x6FUx8BiAn+3H7Oo+8kiJLKsIBJ7ygleg6jxH03H6JU2dKRQDHMs9d/m3HpSvVEEK8+k/HmZWX63OoxrUFmaG4Tlg700GLbpdhkVZh18S8wuKPCKAk2qhGLeZa4gLUX+4NGiUZYYGmuq+CcGcXaow7o6uGlWIw1dYBvQE58ONrgBIUusmgKlWphmXBbc7FfoCc8XjmcYQP6ErUAIPCGRKGmCTynLYCFGH5fIZ/vuhOvlOEyi9+lHa/2LYg1c2J3Ze343hL2WslpEVtLuCk9XwcbyIZREeeRk76ksawhqzzbCnwLcxDtxbZhjZ3LE2dhZFK80xYt+lpNUmsSdH41M5kpeFc67V1SNX40pS2Fd5Xijx8zBr2DOOpSMBbEB9jxqKHX/Bejwx5jM+wCpmT2hAKh+V2st/lmf9GQXmfgABR/vmGmfqqh8I9q6x/HB4XtHHTaQf13caGIvKVKFr2lFNSDMwQE5ubaUA8F/WOPLqOTvsuirvSAe5y4VzPngDjsaeRl52E6btEIyiPqt8vIwXREjfi552OcXmC/iuvZduM41kx18GbkijJ/QnxRnjwF26xRy8k=}
